version: "3.9"  # optional since v1.27.0
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      REDIS_URI: $REDIS_URI
      REDIS_PASSWORD: $REDIS_PASSWORD
      SESSION: $SESSION
